import { runPipeline } from "./pipeline";
import type { RasterSource } from "./rasterize";
import type { DitherSettings } from "@/components/dither/DitherTool";

export type ExportPayload = {
  width: number;
  height: number;
  algorithm: DitherSettings["algorithm"];
  settings: Omit<DitherSettings, "renderScale">;
  dots: [number, number][];
};

export function buildExport(
  source: RasterSource,
  settings: DitherSettings,
): ExportPayload {
  const fullQuality: DitherSettings = { ...settings, renderScale: 1 };
  const result = runPipeline(source, fullQuality);
  const dots: [number, number][] = [];
  for (let y = 0; y < result.height; y++) {
    for (let x = 0; x < result.width; x++) {
      if (result.bitmap[y * result.width + x]) dots.push([x, y]);
    }
  }
  const { renderScale: _ignored, ...exportSettings } = fullQuality;
  return {
    width: result.width,
    height: result.height,
    algorithm: fullQuality.algorithm,
    settings: exportSettings,
    dots,
  };
}

export function toJson(payload: ExportPayload): string {
  return JSON.stringify(payload, null, 2);
}

export function toJsSnippet(payload: ExportPayload): string {
  const { width, height, algorithm, dots } = payload;
  const dotsSrc = dots.map(([x, y]) => `[${x},${y}]`).join(",");
  return `// Generated by oklab.world/tools/dither — algorithm: ${algorithm}
const dots = [${dotsSrc}];
const width = ${width};
const height = ${height};

export function renderDots(canvas, { color = "#111", radius = 1 } = {}) {
  const ctx = canvas.getContext("2d");
  const dpr = window.devicePixelRatio || 1;
  const cw = canvas.clientWidth || width;
  const ch = canvas.clientHeight || height;
  canvas.width = cw * dpr;
  canvas.height = ch * dpr;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.fillStyle = color;
  const sx = cw / width;
  const sy = ch / height;
  for (const [x, y] of dots) {
    ctx.beginPath();
    ctx.arc(x * sx + sx / 2, y * sy + sy / 2, radius, 0, Math.PI * 2);
    ctx.fill();
  }
}
`;
}

export function downloadJson(payload: ExportPayload, filename?: string): void {
  const name = filename ?? `dither-${Date.now()}.json`;
  const blob = new Blob([toJson(payload)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export async function copyJsSnippet(payload: ExportPayload): Promise<void> {
  await navigator.clipboard.writeText(toJsSnippet(payload));
}
